// react-ui/src/components/alarmItem.js
import React from 'react';
import { Link } from 'react-router-dom';

const getFormattedUei = uei => {
  let ret = uei.replace(/^.*\//g, '');
  ret = ret.search(/_/) === -1 ? ret.replace(/([A-Z])/g, ' $1') : ret.replace('_', ' ');
  return ret.charAt(0).toUpperCase() + ret.slice(1);
}

const AlarmItem = ({ alarm }) => (
  <div className="panel panel-default">
    <div className="panel-heading">
      <Link to={`/alarms/${alarm.id}`}>
        <h3 className="panel-title">{ getFormattedUei(alarm.uei) }</h3>
      </Link>
    </div>
    <div className="panel-body">
      { alarm.logMessage }
    </div>
  </div>
)

export default AlarmItem

// angular-ui/src/app/alarm-item/alarm-item.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-alarm-item',
  templateUrl: './alarm-item.component.html'
})
export class AlarmItemComponent {

  @Input()
  alarm: Object;

  getFormattedUei() : string {
    let ret = this.alarm['uei'].replace(/^.*\//g, '');
    ret = ret.search(/_/) === -1 ? ret.replace(/([A-Z])/g, ' $1') : ret.replace('_', ' ');
    return ret.charAt(0).toUpperCase() + ret.slice(1);
  }

}

<div class="panel panel-default">
  <div class="panel-heading" [routerLink]="['/alarms', alarm.id]">
    <h3 class="panel-title">{{ getFormattedUei() }}</h3>
  </div>
  <div class="panel-body">
    {{ alarm.logMessage }}
  </div>
</div>
