// angular-ui/src/app/alarm/alarm.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from "@angular/router";
import { Subscription } from 'rxjs/Rx';

import { AlarmsService } from '../alarms.service';

@Component({
  selector: 'app-alarm',
  templateUrl: './alarm.component.html'
})
export class AlarmComponent {

  alarm: Object;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private alarmsService: AlarmsService
  ) {
    let id = route.snapshot.params['id'];
    alarmsService.getAlarm(id)
      .then(alarm => this.alarm = alarm)
      .catch(error => console.error(error));
  }

  goBack() {
    this.router.navigate(['../']);
  }

  getBodyClass() : string {
    return `panel-body ${this.alarm['severity']}`;
  }

}

<p>
  <button type="button" class="btn btn-danger" (click)="goBack()">
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
  </button>
</p>

<div class="panel panel-default" *ngIf="alarm != null; else elseBlock">
  <div class="panel-heading">
    <h3 class="panel-title">Alarm ID {{ alarm.id }}</h3>
  </div>
  <div [class]="getBodyClass()" [innerHTML]="alarm.description"></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Parameters</h3>
  </div>
  <div [class]="getBodyClass()">
    <table class="table table-condensed table-hover" *ngIf="alarm.parameters && alarm.parameters.length > 0; else noParams">
      <tr *ngFor="let p of alarm.parameters">
        <th>{{ p.name }}</th>
        <td>{{ p.value }}</td>
      </tr>
    </table>
    <ng-template #noParams>
      <p>No Parameters.</p>
    </ng-template>
  </div>
</div>

<ng-template #elseBlock>
  <div className="jumbotron">
    Looks like you haven't selected an alarm
  </div>
</ng-template>

// react-ui/src/components/Alarm.js
import React from 'react';

import BackButton from './BackButton';
import AlarmsService from '../services/alarms';

export default class Alarm extends React.Component {

  constructor() {
    super();
    this.state = {
      alarm: null
    }
  }

  componentWillMount() {
    AlarmsService.getAlarm(this.props.match.params.id).then(alarm => {
      this.setState({alarm});
    });
  }

  render() {
    let { alarm } = this.state;
    const panelBodyClass = `panel-body ${alarm ? alarm.severity : ''}`;
    return (
    <div>
      <BackButton/>
      { alarm ?
        <div>
          <div className="panel panel-default">
            <div className="panel-heading">
              <h3 className="panel-title">Alarm ID { alarm.id }</h3>
            </div>
            <div className={panelBodyClass} dangerouslySetInnerHTML={ {__html: alarm.description} }></div>
            <div className="panel-footer clearfix">
              <div className="pull-right">{ new Date(alarm.lastEventTime).toString() }</div>
            </div>            
          </div>
          { alarm.parameters && alarm.parameters.length > 0 ?
            <div className="panel panel-default">
              <div className="panel-heading">
                <h3 className="panel-title">Parameters</h3>
              </div>
              <div className={panelBodyClass}>
                <table className="table table-condensed table-hover">
                  <tbody>
                  {                
                    alarm.parameters.map(p => (
                      <tr key={p.name}>
                        <th>{ p.name }</th>
                        <td>{ p.value }</td>
                      </tr>
                    ))
                  }
                  </tbody>
                </table>
              </div>
            </div>
            : ''
          }
        </div>
      :
        <div className="jumbotron">Looks like you haven't selected an alarm</div>
      }
    </div>
    );
  }

}
