// angular-ui/src/app/alarms/alarms.component.ts
import { Component } from '@angular/core';

import { AlarmsService } from '../alarms.service';

@Component({
  selector: 'app-alarms',
  templateUrl: './alarms.component.html'
})
export class AlarmsComponent {

  loading = false;
  alarms: Object[] = [];

  constructor(private alarmsService: AlarmsService) { }

  fetchAlarms() {
    this.loading = true;
    this.alarmsService.getAlarms()
      .then(alarms => {
        this.loading = false;
        this.alarms = alarms;
      })
      .catch(error => {
        this.loading = false;
        console.error(error);
      });
  }

}

<p>
  <button class="btn btn-primary" type="button" (click)="fetchAlarms()">
    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Load Alarms
  </button>
</p>

<div class="jumbotron" *ngIf="loading">
  <h3>Loading ... Please wait.</h3>
</div>

<app-alarm-item *ngFor="let alarm of alarms" [alarm]="alarm"></app-alarm-item>

// react-ui/src/components/alarms.js
import React from 'react';

import AlarmItem from './alarmItem';
import AlarmsService from '../services/alarms';

export default class Alarms extends React.Component {

  constructor() {
    super();
    this.state = {
      loading: false,
      alarms: []      
    }
  }

  fetchAlarms() {
    this.setState({loading: true});
    AlarmsService.getAlarms().then(data => {
      console.log(data);
      this.setState({loading: false, alarms: data.alarm});
    });
  }

  render() {
    let { loading, alarms } = this.state;
    return(
      loading ?
      <div className="jumbotron">
        <h3>Loading ... Please wait.</h3>
      </div>
      :
      <div>
        <p>
          <button className="btn btn-primary" type="button" onClick={() => this.fetchAlarms()}>
            <span className="glyphicon glyphicon-refresh" aria-hidden="true"></span> Load Alarms
          </button>
        </p>
        {
          alarms.map(alarm => <AlarmItem key={alarm.id} alarm={alarm} />)
        }
      </div>
    );
  }
}
