// angular-ui/src/app/alarm/alarm.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from "@angular/router";
import { Subscription } from 'rxjs/Rx';

import { AlarmsService } from '../alarms.service';

@Component({
  selector: 'app-alarm',
  templateUrl: './alarm.component.html'
})
export class AlarmComponent {

  alarm: Object;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private alarmsService: AlarmsService
  ) {
    let id = route.snapshot.params['id'];
    alarmsService.getAlarm(id)
      .then(alarm => this.alarm = alarm)
      .catch(error => console.error(error));
  }

  goBack() {
    this.router.navigate(['../']);
  }

}

<p>
  <button type="button" class="btn btn-danger" (click)="goBack()">
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
  </button>
</p>

<div class="panel panel-default" *ngIf="alarm != null; else elseBlock">
  <div class="panel-heading">
    <h3 class="panel-title">Alarm ID {{ alarm.id }}</h3>
  </div>
  <div class="panel-body" [innerHTML]="alarm.description"></div>
</div>

<ng-template #elseBlock>
  <div className="jumbotron">
    Looks like you haven't selected an alarm
  </div>
</ng-template>

// react-ui/src/components/alarm.js
import React from 'react';

import BackButton from './back';
import AlarmsService from '../services/alarms';

export default class Alarm extends React.Component {

  constructor() {
    super();
    this.state = {
      alarm: null
    }
  }

  componentWillMount() {
    AlarmsService.getAlarm(this.props.match.params.id).then(alarm => {
      this.setState({alarm});
    });
  }

  render() {
    let { alarm } = this.state;
    return (
      alarm ?
      <div>
        <BackButton/>
        <div className="panel panel-default">
          <div className="panel-heading">
            <h3 className="panel-title">Alarm ID { alarm.id }</h3>
          </div>
          <div className="panel-body" dangerouslySetInnerHTML={ {__html: alarm.description} }/>
        </div>
      </div>
      :
      <div>
        <BackButton/>
        <div className="jumbotron">Looks like you haven't selected an alarm</div>
      </div>
    );
  }

}
