// react-redux-ui/src/components/Alarms.js
import React from 'react';
import PropTypes from 'prop-types';

import AlarmItem from './AlarmItem';

const Alarms = ({ data: { alarms, loading }, setAlarm, fetchAlarms }) => {
  return(
    loading ?
    <div className="jumbotron">
      <h3>Loading ... Please wait.</h3>
    </div>
    :
    <div>
      <p>
        <button className="btn btn-primary" type="button" onClick={fetchAlarms}>
          <span className="glyphicon glyphicon-refresh" aria-hidden="true"></span> Load Alarms
        </button>
      </p>
      {
        alarms.map(alarm =>
          <AlarmItem
            key={alarm.id}
            alarm={alarm}
            onClick={() => setAlarm(alarm)}/>
        )
      }
    </div>
  );
};

Alarms.propTypes = {
  data: PropTypes.shape({
    alarms: PropTypes.array.isRequired,
    loading: PropTypes.bool.isRequired
  }),
  fetchAlarms: PropTypes.func.isRequired,
  setAlarm: PropTypes.func.isRequired
}

export default Alarms;

// angular-ui/src/app/alarms/alarms.component.ts
import { Component } from '@angular/core';

import { AlarmsService } from '../alarms.service';

@Component({
  selector: 'app-alarms',
  templateUrl: './alarms.component.html'
})
export class AlarmsComponent {

  loading = false;
  alarms: Object[] = [];

  constructor(private alarmsService: AlarmsService) { }

  fetchAlarms() {
    this.loading = true;
    this.alarmsService.getAlarms()
      .then(alarms => {
        this.loading = false;
        this.alarms = alarms;
      })
      .catch(error => {
        this.loading = false;
        console.error(error);
      });
  }

}

<p>
  <button class="btn btn-primary" type="button" (click)="fetchAlarms()">
    <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Load Alarms
  </button>
</p>

<div class="jumbotron" *ngIf="loading">
  <h3>Loading ... Please wait.</h3>
</div>

<app-alarm-item *ngFor="let alarm of alarms" [alarm]="alarm"></app-alarm-item>
